
package Vista;

import Conexion.CConexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

public class FormularioCRUDPrincipal extends javax.swing.JFrame {

    public void añadirA(){
    FormularioCRUDA longitud = new FormularioCRUDA();
    longitud.setSize(500, 500);  // Cambiado a un tamaño más razonable
    this.panelvari.removeAll();  // Limpiar el panel
    this.panelvari.setLayout(new BorderLayout());  // Asegurarse de que usa BorderLayout
    this.panelvari.add(longitud, BorderLayout.CENTER);  // Añadir el JPanel
    this.panelvari.revalidate();  // Revalidar
    this.panelvari.repaint();  // Repintar
    this.panelvari.doLayout();  // Ajustar el layout
}
    public void añadirD(){
    FormularioCRUDD longitud = new FormularioCRUDD();
    longitud.setSize(500, 500);  // Cambiado a un tamaño más razonable
    this.panelvari.removeAll();  // Limpiar el panel
    this.panelvari.setLayout(new BorderLayout());  // Asegurarse de que usa BorderLayout
    this.panelvari.add(longitud, BorderLayout.CENTER);  // Añadir el JPanel
    this.panelvari.revalidate();  // Revalidar
    this.panelvari.repaint();  // Repintar
    this.panelvari.doLayout();  // Ajustar el layout
}
    public void añadirP(){
    FormularioCRUDT longitud = new FormularioCRUDT();
    longitud.setSize(500, 500);  // Cambiado a un tamaño más razonable
    this.panelvari.removeAll();  // Limpiar el panel
    this.panelvari.setLayout(new BorderLayout());  // Asegurarse de que usa BorderLayout
    this.panelvari.add(longitud, BorderLayout.CENTER);  // Añadir el JPanel
    this.panelvari.revalidate();  // Revalidar
    this.panelvari.repaint();  // Repintar
    this.panelvari.doLayout();  // Ajustar el layout
}
    public void añadirCita(){
    FormularioCRUDP longitud = new FormularioCRUDP();
    longitud.setSize(500, 500);  // Cambiado a un tamaño más razonable
    this.panelvari.removeAll();  // Limpiar el panel
    this.panelvari.setLayout(new BorderLayout());  // Asegurarse de que usa BorderLayout
    this.panelvari.add(longitud, BorderLayout.CENTER);  // Añadir el JPanel
    this.panelvari.revalidate();  // Revalidar
    this.panelvari.repaint();  // Repintar
    this.panelvari.doLayout();  // Ajustar el layout
}
    public FormularioCRUDPrincipal() {
        initComponents();
        
        CConexion objetoConexion = new CConexion();
        objetoConexion.establecerConexion();
    formulario();
    }

    // Método para configurar el formulario
    private void formulario() {
        this.setTitle("Gestion de la de Tratamientos de Pacientes de Clinica");
        this.setLocationRelativeTo(null); // Centrar en la pantalla
        this.setResizable(false); // Deshabilitar redimensionamiento
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Cerrar la aplicación al salir
        
        // Establecer dimensiones fijas
        this.setSize(new Dimension(1150, 450));
        
     
        
        // Cambiar el fondo de la ventana y los paneles
        this.getContentPane().setBackground(new Color(255, 255, 255));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnA = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCitas = new javax.swing.JButton();
        panelvari = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Seleccionar Tabla", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        btnA.setBackground(new java.awt.Color(153, 255, 153));
        btnA.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnA.setText("Paciente");
        btnA.setToolTipText("");
        btnA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnD.setBackground(new java.awt.Color(153, 255, 153));
        btnD.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnD.setText("Doctores");
        btnD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });

        btnP.setBackground(new java.awt.Color(153, 255, 153));
        btnP.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnP.setText("Tratamieno");
        btnP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnCitas.setBackground(new java.awt.Color(153, 255, 153));
        btnCitas.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCitas.setText("Citas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnA)
                .addGap(27, 27, 27)
                .addComponent(btnD)
                .addGap(18, 18, 18)
                .addComponent(btnP)
                .addGap(18, 18, 18)
                .addComponent(btnCitas)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelvari.setBackground(new java.awt.Color(255, 255, 255));
        panelvari.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione Tabla");

        javax.swing.GroupLayout panelvariLayout = new javax.swing.GroupLayout(panelvari);
        panelvari.setLayout(panelvariLayout);
        panelvariLayout.setHorizontalGroup(
            panelvariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        panelvariLayout.setVerticalGroup(
            panelvariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelvariLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelvari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelvari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
       
    }//GEN-LAST:event_btnAActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
       
    }//GEN-LAST:event_btnDActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
       
    }//GEN-LAST:event_btnPActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed
public void agregarAlumnoListener(ActionListener listener){
    
        this.btnA.addActionListener(listener);
    
    }
    public void agregarDocenteListener(ActionListener listener){
    
        this.btnD.addActionListener(listener);
    
    }
    public void agregarPersonalListener(ActionListener listener){
    
        this.btnP.addActionListener(listener);
    
    }
    
    public void agregarCitalListener(ActionListener listener){
    
        this.btnCitas.addActionListener(listener);
        
    }
    
    public void agregarSalirListener(ActionListener listener){
    
        this.btnSalir.addActionListener(listener);
    
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCRUDPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCRUDPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCRUDPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCRUDPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCRUDPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelvari;
    // End of variables declaration//GEN-END:variables
}
